locale: es
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
#publish_mode: editorial_workflow # Allows you to save drafts before publishing them
media_folder: static/uploads # Media files will be stored in the repo under static/images/uploads
public_folder: /uploads # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: 'productos' # Used in routes, e.g., /admin/collections/blog
    label: 'Productos' # Used in the UI
    label_singular: 'Producto'
    extension: 'md'
    description: 'Colección de productos publicados'
    folder: 'contenido/productos' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Nombre', name: 'title', widget: 'string' }
      - { label: 'Descripcion Corta', name: 'description', widget: 'string' }
      - { label: 'Imagen', name: 'imagen', widget: 'image' }
      - { label: 'Cuerpo', name: 'cuerpo', widget: 'markdown' }
      - {
          label: 'Categoria',
          widget: 'relation',
          name: 'productoCategoria',
          collection: 'categoria',
          valueField: 'title',
          displayFields: ['title', 'descripcion'],
          searchFields: ['title', 'descripcion', 'cuerpo'],
        }
  - name: 'categoria'
    label: 'Categoría'
    folder: 'contenido/categorias'
    slug: '{{slug}}'
    create: true
    fields:
      - { label: 'Nombre', name: 'title', widget: 'string' }
