locale: es
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
#publish_mode: editorial_workflow # Allows you to save drafts before publishing them
media_folder: static/uploads # Media files will be stored in the repo under static/images/uploads
public_folder: /uploads # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: 'productos' # Used in routes, e.g., /admin/collections/blog
    label: 'Productos' # Used in the UI
    label_singular: 'Producto'
    extension: 'md'
    description: 'Colección de productos publicados'
    folder: 'src/data/productos' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Nombre', name: 'title', widget: 'string' }
      - { label: 'Descripcion Corta', name: 'description', widget: 'string' }
      - { label: 'Imagen', name: 'imagen', widget: 'image' }
      - { label: 'Precio', name: 'precio', widget: 'number' }
      - { label: 'Descuento (%)', name: 'descuento', widget: 'number' }
      - { label: 'Cuerpo', name: 'cuerpo', widget: 'markdown' }
      - {
          label: 'Categoria',
          widget: 'relation',
          file: 'categorias',
          collection: 'categorias',
          valueField: 'categorias',
          displayFields: ['categorias', 'nombre'],
          searchFields: ['nombre'],
        }
      - {
          label: 'Mostrar en página de inicio',
          name: 'mostrarInicio',
          widget: 'select',
          options: ['Si', 'No'],
        }
  # - name: 'categoria'
  #   label: 'Categoría'
  #   folder: 'src/data/categorias'
  #   slug: '{{slug}}'
  #   create: true
  #   fields:
  #     - { label: 'Nombre', name: 'title', widget: 'string' }
  - label: 'Sitio'
    name: 'sitio'
    files:
      - label: 'Banners'
        name: 'banners'
        file: 'src/data/banners.yml'
        fields:
          - {
              label: 'Nombre de la tienda',
              name: 'title',
              widget: string,
              required: false,
            }
          - {
              label: 'Dirección',
              name: 'direccion',
              widget: string,
              required: false,
            }
          - { label: 'Logo', name: 'imagen', widget: 'image', required: false }
          - { label: 'Icono', name: 'icono', widget: 'image', required: false }
          - { label: 'Whatsapp', name: 'whatsapp', widget: 'string' }
          - {
              label: 'Facebook',
              name: 'facebook',
              widget: 'string',
              required: false,
            }
          - {
              label: 'Instagram',
              name: 'instagram',
              widget: 'string',
              required: false,
            }
          - {
              label: 'Twitter',
              name: 'twitter',
              widget: 'string',
              required: false,
            }
          - {
              label: 'Pinterest',
              name: 'pinterest',
              widget: 'string',
              required: false,
            }
          - { label: 'Email', name: 'email', widget: 'string', required: false }
      - label: 'Datos de la tienda'
        name: 'info'
        file: 'src/data/info.yml'
        fields:
          - {
              label: 'Nombre de la tienda',
              name: 'title',
              widget: string,
              required: false,
            }
          - {
              label: 'Dirección',
              name: 'direccion',
              widget: string,
              required: false,
            }
          - { label: 'Logo', name: 'imagen', widget: 'image', required: false }
          - { label: 'Icono', name: 'icono', widget: 'image', required: false }
          - { label: 'Whatsapp', name: 'whatsapp', widget: 'string' }
          - {
              label: 'Facebook',
              name: 'facebook',
              widget: 'string',
              required: false,
            }
          - {
              label: 'Instagram',
              name: 'instagram',
              widget: 'string',
              required: false,
            }
          - {
              label: 'Twitter',
              name: 'twitter',
              widget: 'string',
              required: false,
            }
          - {
              label: 'Pinterest',
              name: 'pinterest',
              widget: 'string',
              required: false,
            }
          - { label: 'Email', name: 'email', widget: 'string', required: false }
      - label: 'Categorias'
        name: 'categorias'
        file: 'source/data/categorias.yml'
        fields:
          - {
              label: 'Categorias',
              widget: 'list',
              name: 'categorias',
              label_singular: 'Categoría',
              field: { label: 'Nombre', name: 'nombre', widget: 'string' },
            }
